### ISSUE TITLE
Data update?

### ISSUE THREAD

**Issue by eddelbuettel** [NYTimes/gun-sales#18]
@gka: Didn't you mention new data in a tweet the other day?

**Comment by gka** [comment]
can I send you the data file? don't have time to update right now

**Comment by eddelbuettel** [comment]
Sure, assuming it is in  the same format or else I would not know how you normalized.

There is also an open issue in that we haven't documented all URLs as I recall.   But no hurry; I am also a little busy.  We can always clean up next month....

**Comment by gka** [comment]
This repo got too complicated for me to update the data. But you are free to copy the updated data from this repo https://github.com/gka/gunsales

**Comment by eddelbuettel** [comment]
You closed the issue without addressing it.  Neither this repo, not the one you point to, has _any_ documentation about the _source_ of the data.  No URL, no sourcing script, nothing.   

I was hoping we could do better.

**Comment by gka** [comment]
thought this was clear?

source is this PDF
https://www.fbi.gov/file-repository/nics_firearm_checks_-_month_year_by_state_type.pdf/view

which I convert into csv using Tabula, updating this file 
https://github.com/gka/gunsales/blob/master/data/ncis_bystate_bymonth_bytype.csv

unfortunately there is no easy automatic process to do this

**Comment by gka** [comment]
the readme clearly states (and always has) that

> The source data comes from the [FBI's National Instant Criminal Background Check System](https://www.fbi.gov/about-us/cjis/nics), and was converted from the original [PDF format](https://www.fbi.gov/about-us/cjis/nics/reports/nics_firearm_checks_-_month_year_by_state_type.pdf) to CSV using [Tabula](http://tabula.technology/).

**Comment by eddelbuettel** [comment]
> thought this was clear?

I would not keep asking if it was. You gave a reference to a _website_ which is different from documenting a source.  An actual link is _much_ better (even if its format is inconvenient, it is fine to say so) so thanks for finally stating it.

But that is also only one of two files.  The other file, [popdata.csv](https://raw.githubusercontent.com/NYTimes/gunsales/master/inst/rawdata/population.csv) is still what I would call undocumented as I never managed to find a matching series on the US Census website.

**Comment by gka** [comment]
* the PDF was always linked directly (although the FBI at some point moved it to a different URL which is now fixed in the readme)
* the population data was never even used in our story, and thus can be dropped from the repo entirely

**Comment by eddelbuettel** [comment]
The population data is used in several of the charts to normalize the growth by population, and that strikes me as darn good practice.  

The _precise_ source for that file is still missing.

**Comment by gka** [comment]
I would rather drop it than go through it and find the source again. Normalizing by population did not reveal anything new, the normalization as percent of national gunsales was a lot more insightful.

**Comment by eddelbuettel** [comment]
That is an aspect one can have different views on.

**Comment by gka** [comment]
The purpose of this repo was to make transparent the data analysis that went into this particular story. The population normalization was something we tried and discarded before publishing. Thus no need to keep it here. I am sure there are better sources for monthly state by state population estimates, probably even readily available as R package, than the CSV I was using.

**Comment by eddelbuettel** [comment]
If you could share any detail you recall from first fetching that series, it would help me.  There are (as I recall) different sets of estimates available at the Census site from alternative methodologies for projecting.  I am sure I can find something at FRED, or Quandl, or some other site.  It won't be identical but as you note it won't bend the arc of the story told.

Having two series is a nice way to motivate merging etc.  If I find some time I still plan to use this data set and analysis to set up a little comparison of possible approaches e.g. dplyr vs data.table.  It is still a little muddled now.
